apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s
spec:
  selector:
    matchLabels:
      app: backend-k8s
  template:
    metadata:
      labels:
        app: backend-k8s
    spec:
      containers:
      - name: backend-k8s
        image: aptroide/backend-k8s:V3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s
spec:
  type: NodePort
  selector:
    app: backend-k8s
  ports:
  - port: 3000
    targetPort: 3000

