apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s
spec:
  selector:
    matchLabels:
      app: frontend-k8s
  template:
    metadata:
      labels:
        app: frontend-k8s
    spec:
      containers:
      - name: frontend-k8s
        image: aptroide/fronted-k8s:V3.1
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s
spec:
  type: NodePort
  selector:
    app: frontend-k8s
  ports:
  - port: 3000
    targetPort: 3000

