apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-k8s
  template:
    metadata:
      labels:
        app: db-k8s
    spec:
      containers:
      - name: db-k8s
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db-k8s
spec:
  selector:
    app: db-k8s
  ports:
  - port: 27017

